name = input("What is your name?")
q1 = input("What did you like/dislike about Code Academy?")
q2 = input("What did you enjoy most about the class?")
q3 = input("How was the pace of the class?  (good, too fast, too slow)")
q4 = input("What would you change about the class?")
q5 = input("Would you recommend this class to a friend? Why/why not?")

text_file = open("Output.txt", "w")
text_file.write("%s" %(name))
text_file.write("%s" %(q1) + "\n")
text_file.write("%s" %(q2) + "\n")
text_file.write("%s" %(q3) +"\n")
text_file.write("%s" %(q4) + "\n")
text_file.write("%s" %(q5))
text_file.close()
